BotConfig:
  TOKEN: "6917416058:AAEEEoLdn0VxfHrUJn5LRHb_0qEZ8VRnHMw"

Cookies:
  value: "1SGDS2981-habKgl0bhZt4DjW6ishgrDUXYOZzSXsBmQAIHag4-iYAso89QFD6ZT-s_ct5APChSFgGWw5KV07ANJ5qRLCh3Rd19c2f2KV6_qUeXqZ7Uq1h8ZGM9DGE-RPOC2k8B01d5q1x4mdHrLunISH4fvVZbuhKCvFDh43SWvu8bW1foX6IhA1KfDR1uxScuRzqX6b600jZ9rAoaeFgA"

Logging:
  level: INFO
