BotConfig:
  TOKEN: "6917416058:AAEEEoLdn0VxfHrUJn5LRHb_0qEZ8VRnHMw"

Cookies:
  value: "1SGDS298I-habKgl0bhZt4DjW6ishgrDUXyOZzsXsBmQAIHag4-iYAso89QFD6ZT-s_ct5APChSFgGWw5KVO7ANJ5qRLCh3RdI9c2f2KV6_qUeXqZ7Uq1h8ZGM9DGE-RPOC2k8BO1d5q1x4mdHrLunISH4fvVZbuhKCvFDh43SWvu8bW1foX6IhA1KfDR1uxScuRzqX6b6OOjZ9rAoaeFgA"
Logging:
  level: INFO
